### PR TITLE
Fix writing setup name for n5

### PR DESCRIPTION
**Pull request by K-Meech**
For https://github.com/mobie/mobie-viewer-fiji/issues/655

Fixes writing specific view setup names for n5 + adds a test for this

### CODE REVIEW

**Comment by tischi** [comment]
We should rename this class: https://github.com/mobie/mobie-io/blob/6158146b26b078967cb9fe004852962c7c685954/src/main/java/org/embl/mobie/io/n5/writers/WriteImgPlusToN5.java

`ImgPlus` is in fact something that exists as well: https://javadoc.scijava.org/ImageJ/net/imagej/ImgPlus.html
But we want `ImagePlus`.

**Comment by K-Meech** [comment]
Good point @tischi! I didn't know this - I'll rename the relevant classes.

**Comment by K-Meech** [comment]
I renamed the classes @tischi

**Review by KateMoreva — APPROVED** [review]

**Comment by K-Meech** [comment]
I'll go ahead and merge this.

**Pull request merged**
