### PR TITLE
Quick fix v3 reading

### PR DESCRIPTION
**Pull request by KateMoreva**

### CODE REVIEW

**Comment by tischi** [comment]
Please do not forget to bump the path version in the pom.

**Comment by K-Meech** [comment]
Thanks @KateMoreva - yes, this will cause issues with the writing, as it no longer writes the zarrAxisList with the right name 'axes'. I can look into fixing this - if you like? I imagine it will need a custom deserialiser for the axes.

**Comment by KateMoreva** [comment]
> Thanks @KateMoreva - yes, this will cause issues with the writing, as it no longer writes the zarrAxisList with the right name 'axes'. I can look into fixing this - if you like? I imagine it will need a custom deserialiser for the axes.

Yes, we need a custom deserialiser the axes, I can create one later today.

**Comment by K-Meech** [comment]
Ok - sounds good! Thanks!

**Comment by constantinpape** [comment]
Hey @K-Meech,
could you check if this can be merged? Then we can move ahead with the release :).

**Comment by K-Meech** [comment]
I should have time to look later today :)

**Review by K-Meech — COMMENTED** [review]
Thanks @KateMoreva! This fixes all the issues :) 
I do think a simpler solution is possible though. At the moment, you introduce new json dependencies + explicitly convert a lot of the multiscales to json. I think you can let the library do more of the hard work!

E.g. If you add an adapter for OmeZarrMultiscales, that only implemented a ```JsonSerializer<OmeZarrMultiscales>``` (and no deserialiser), then you could have something like this: 
```
@Override
    public JsonElement serialize(OmeZarrMultiscales src, Type typeOfSrc, JsonSerializationContext context) {
        JsonObject obj = new JsonObject();
        obj.add("axes", context.serialize(src.zarrAxisList));
        obj.add("datasets", context.serialize(src.datasets));
and so on....
````
This way you can change the name of the zarrAxesList to 'axes', and let gson convert everything else.  Would that work? I think it might simplify the code by quite a bit.

**Comment by tischi** [comment]
I second @K-Meech's suggestion! I did the same mistake (given that you did not do this on purpose) myself in the past. Now I just create a Java class for everything that I want to serialize/deserialize and let JSON do all the work....it really changed my life 😄 !

**Comment by tischi** [comment]
...I did not look at the code in detail, but maybe you could even serialize the whole `OmeZarrMultiscales` in one go (if you give the fields the same names as in the spec, and if you mark all fields that you do not want to serialize as `transient`)

**Comment by KateMoreva** [comment]
> JsonObject obj = new JsonObject();
>         obj.add("axes", context.serialize(src.zarrAxisList));
>         obj.add("datasets", context.serialize(src.datasets));

Thank you a lot for the advice!
Yes, this would be more elegant. Although our adapter would give us more flexibility in the future, I think we do not need this for now.

**Comment by constantinpape** [comment]
Thanks for looking into this again @KateMoreva. I think this is good to go now, can we merge it and then continue with the release, @K-Meech @tischi?

**Comment by tischi** [comment]
@KateMoreva 

Thanks for all the great work!

Could you please
1. bump the minor version in the pom?
2. merge it?

**Review by K-Meech — APPROVED** [review]
Looks good to me! Thanks @KateMoreva!

**Pull request merged**
