### PR TITLE
Parent pom scijava 33.2.0

### PR DESCRIPTION
**Pull request by tischi**
@tpietzsch `SimpleCacheArrayLoader` now also wants the `cellDimensions` in the `loadArray` method, but we never used them...is it OK just to change the method in our implementations and ignore that argument? It seems to mostly work...

@constantinpape @KateMoreva 
Only this test fails in this branch: 
`OmeZarrWithWriterTest.checkOmeZarrLoopBack:359->writeImageAndGetPath:201 ? Runtime`
Could you have a look?

Context, we need to update to new scijava parent pom with new versions of many things.

### CODE REVIEW

**Comment by constantinpape** [comment]
@tischi the tests on develop / main are still not fully up to date, since https://github.com/mobie/mobie-io/pull/124 is not merged yet. Before I have any look at the tests we should merge them, otherwise we will duplicate work. I was waiting with merging it for some feedback from you or @KateMoreva, but we can also go ahead and merge it now.

**Comment by tischi** [comment]
@constantinpape I merged your latest changes into `develop` and `main` and this `scijava32` branch.

**Comment by tischi** [comment]
Similar situation:

```
[ERROR] Errors: 
[ERROR]   NGFFWriterTest.checkOmeZarrLoopBack:359->writeImageAndGetPath:201 ? Runtime ja...
[ERROR]   OmeZarrWithWriterTest.checkOmeZarrLoopBack:359->writeImageAndGetPath:201 ? Runtime
[INFO] 
[ERROR] Tests run: 202, Failures: 0, Errors: 2, Skipped: 4
```

Any ideas?

**Comment by constantinpape** [comment]
I can't reproduce this locally: for me all tests pass. 

And the test failure here seems to be some unrelated mvn issue:
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:3.2.0:jar (default-jar) on project mobie-io: Execution default-jar of goal org.apache.maven.plugins:maven-jar-plugin:3.2.0:jar failed: Plugin org.apache.maven.plugins:maven-jar-plugin:3.2.0 or one of its dependencies could not be resolved: Failed to collect dependencies at org.apache.maven.plugins:maven-jar-plugin:jar:3.2.0 -> org.apache.maven:maven-archiver:jar:3.5.0 -> org.codehaus.plexus:plexus-archiver:jar:4.2.0 -> org.apache.commons:commons-compress:jar:1.19: Failed to read artifact descriptor for org.apache.commons:commons-compress:jar:1.19: Could not transfer artifact org.apache.commons:commons-parent:pom:48 from/to central (https://repo.maven.apache.org/maven2): transfer failed for https://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/48/commons-parent-48.pom: Connection timed out (Read failed) -> [Help 1]
```

**Comment by tischi** [comment]
@constantinpape seems like on github there are less tests (99) running than locally (202) https://github.com/mobie/mobie-io/actions/runs/3113639913/jobs/5048524650#step:6:263 is this expected?

@imagejan @ctrueden do you know what this error could be due to? https://github.com/mobie/mobie-io/actions/runs/3113639913/jobs/5048524650#step:6:273

**Comment by constantinpape** [comment]
For me only 99 tests run locally:
```
[INFO] 
[INFO] Results:
[INFO] 
[WARNING] Tests run: 99, Failures: 0, Errors: 0, Skipped: 2
```

**Comment by constantinpape** [comment]
My guess is that you still have both the old and new tests running locally.

**Comment by tischi** [comment]
@constantinpape How do you run the tests?
I do:

```
> mvn test
```

and I get: `[ERROR] Tests run: 202, Failures: 0, Errors: 2, Skipped: 4`

**Comment by imagejan** [comment]
@tischi is your working copy clean?

**Comment by tischi** [comment]
`mvn clean test` does the trick! Thanks @imagejan!

I am still not sure about the `SimpleCacheArrayLoader`, but I guess that's why we have tests....if they all pass...it should be fine....I will merge it then.

**Pull request merged**
