### PR TITLE
Add methods to write to S3

### PR DESCRIPTION
**Pull request by tischi**

### CODE REVIEW

**Review by constantinpape — COMMENTED** [review]
This looks straight forward.
Just one question: are you considering that `uri` might exist and that this method will overwrite it?
(Actually I am not 100% sure it has the same behavior w.r.t. this for `s3.putObject` and `BufferedWriter`)

**Comment by tischi** [comment]
> are you considering that uri might exist and that this method will overwrite it?

I had a look and I think that both implementations will overwrite an existing object. 

Should we reflect this in the method name or just add it to the Javadoc?
 
Do you think that's OK? 

Then the upstream code would need to check whether this is an issue or not (using the `exists(String uri)` method in our code).

**Comment by K-Meech** [comment]
Looks good to me! Does this somehow check you have the right S3 credentials?

**Comment by constantinpape** [comment]
> Should we reflect this in the method name or just add it to the Javadoc?

I think it's enough to add it to the javadoc. This is also the behavior I would expect from this method; but it should still be documented explicity.

> Do you think that's OK?
> 
> Then the upstream code would need to check whether this is an issue or not (using the `exists(String uri)` method in our code).

Yes, I think that's fine.

**Comment by tischi** [comment]
Seems to work!

Merge?!

**Comment by K-Meech** [comment]
Go for it! :)

**Pull request merged**
